const endPoints = {
  ALL: "/",
  DANH_SACH_TAT_CA_DON_HANG: "list-all-orders",
  DANH_SACH_TAT_CA_DON_HANG_LOI: "list-all-orders-fail",
  DANH_SACH_DON_HANG_KHACH_VUA_DAT: "list-order-customer-booking",
  DANH_SACH_DON_HANG_DA_NHAN: "list-orders-receiver",
  DANH_SACH_DON_HANG_DA_KIEM_TRA_CHAT_LUONG: "list-orders-checked-quality",
  DANH_SACH_DON_HANG_DANG_KIEM_TRA: "list-orders-checking",
  DANH_SACH_DON_HANG_DA_GIAT_XONG_VA_KIEM_TRA: "list-orders-quality-checked",
  QUAN_LI_LICH_VANG_TAI_XE: "list-driver-absence",
  DANH_SACH_DON_HANG_DA_GIAO: "list-order-assignment",
  SERVICES: "services",
  ORDER: "order",
  POLICY: "policy",
  EXTRACATEGORIES: "extra-categories",
  USERS: "users",
  ORDERMANAGEMENTCUSTOMERSTAFF: "user-management-customer-staff",
  PLACEORDERMANAGEMENTCUSTOMERSTAFF: "order-user-management-customer-staff",
  BRANCH: "branch",
  CHAT: "chat",
  AREAS: "areas",
  PROFILE: "profile",
  CONFIRMCUSTOMERPENDING: "confirm-customer-pending",
  COMPLAINT: '/complaint',
  ADMIN: "/admin",
  LOGIN: "/login",
  REGISTER: "/register",
  FORBIDDEN:"/forbidden",
  CHATWIITHAI: "/chat-with-ai",
  DASHBOARD: "dashboard",
};

export default endPoints;
