const OrderCustomerBooking = [
  {
    "Mã đơn hàng": "LAUNDRY734351",
    "Tên khách hàng": "Pham Thi D",
    "Dịch vụ đã chọn": "Giặt hấp",
    "Trạng thái đơn hàng": "Đã nhận",
    "Thời gian đặt hàng": "2025-02-25 12:38:53",
    "Giá tiền": "61,752 VND",
  },
  {
    "Mã đơn hàng": "LAUNDRY516581",
    "Tên khách hàng": "Le Van C",
    "Dịch vụ đã chọn": "Giặt hấp",
    "Trạng thái đơn hàng": "Đã nhận",
    "Thời gian đặt hàng": "2025-02-16 12:38:53",
    "Giá tiền": "288,868 VND",
  },
  {
    "Mã đơn hàng": "LAUNDRY301124",
    "Tên khách hàng": "Hoang Van E",
    "Dịch vụ đã chọn": "Giặt ủi",
    "Trạng thái đơn hàng": "Đã nhận",
    "Thời gian đặt hàng": "2025-02-25 12:38:53",
    "Giá tiền": "147,617 VND",
  },
  {
    "Mã đơn hàng": "LAUNDRY691124",
    "Tên khách hàng": "Le Van C",
    "Dịch vụ đã chọn": "Giặt ủi",
    "Trạng thái đơn hàng": "Chờ xử lý",
    "Thời gian đặt hàng": "2025-02-18 12:38:53",
    "Giá tiền": "207,407 VND",
  },
  {
    "Mã đơn hàng": "LAUNDRY819774",
    "Tên khách hàng": "Tran Thi B",
    "Dịch vụ đã chọn": "Giặt ủi",
    "Trạng thái đơn hàng": "Đã nhận",
    "Thời gian đặt hàng": "2025-02-18 12:38:53",
    "Giá tiền": "278,085 VND",
  },
  {
    "Mã đơn hàng": "LAUNDRY201464",
    "Tên khách hàng": "Le Van C",
    "Dịch vụ đã chọn": "Giặt hấp",
    "Trạng thái đơn hàng": "Chờ xử lý",
    "Thời gian đặt hàng": "2025-02-17 12:38:53",
    "Giá tiền": "90,289 VND",
  },
  {
    "Mã đơn hàng": "LAUNDRY957510",
    "Tên khách hàng": "Pham Thi D",
    "Dịch vụ đã chọn": "Giặt ủi",
    "Trạng thái đơn hàng": "Đã giặt xong",
    "Thời gian đặt hàng": "2025-02-22 12:38:53",
    "Giá tiền": "86,227 VND",
  },
  {
    "Mã đơn hàng": "LAUNDRY120850",
    "Tên khách hàng": "Tran Thi B",
    "Dịch vụ đã chọn": "Giặt giày",
    "Trạng thái đơn hàng": "Đã giao",
    "Thời gian đặt hàng": "2025-02-18 12:38:53",
    "Giá tiền": "50,185 VND",
  },
  {
    "Mã đơn hàng": "LAUNDRY982255",
    "Tên khách hàng": "Pham Thi D",
    "Dịch vụ đã chọn": "Giặt hấp",
    "Trạng thái đơn hàng": "Chờ xử lý",
    "Thời gian đặt hàng": "2025-02-17 12:38:53",
    "Giá tiền": "237,846 VND",
  },
  {
    "Mã đơn hàng": "LAUNDRY943522",
    "Tên khách hàng": "Le Van C",
    "Dịch vụ đã chọn": "Giặt giày",
    "Trạng thái đơn hàng": "Đã giao",
    "Thời gian đặt hàng": "2025-02-22 12:38:53",
    "Giá tiền": "280,213 VND",
  },
  {
    "Mã đơn hàng": "LAUNDRY294942",
    "Tên khách hàng": "Hoang Van E",
    "Dịch vụ đã chọn": "Giặt giày",
    "Trạng thái đơn hàng": "Đã giao",
    "Thời gian đặt hàng": "2025-02-24 12:38:53",
    "Giá tiền": "138,852 VND",
  },
  {
    "Mã đơn hàng": "LAUNDRY883018",
    "Tên khách hàng": "Nguyen Van A",
    "Dịch vụ đã chọn": "Giặt hấp",
    "Trạng thái đơn hàng": "Đã giao",
    "Thời gian đặt hàng": "2025-02-19 12:38:53",
    "Giá tiền": "138,062 VND",
  },
  {
    "Mã đơn hàng": "LAUNDRY825764",
    "Tên khách hàng": "Pham Thi D",
    "Dịch vụ đã chọn": "Giặt hấp",
    "Trạng thái đơn hàng": "Đã nhận",
    "Thời gian đặt hàng": "2025-02-20 12:38:53",
    "Giá tiền": "58,065 VND",
  },
  {
    "Mã đơn hàng": "LAUNDRY696075",
    "Tên khách hàng": "Hoang Van E",
    "Dịch vụ đã chọn": "Giặt giày",
    "Trạng thái đơn hàng": "Chờ xử lý",
    "Thời gian đặt hàng": "2025-02-24 12:38:53",
    "Giá tiền": "90,801 VND",
  },
  {
    "Mã đơn hàng": "LAUNDRY178306",
    "Tên khách hàng": "Le Van C",
    "Dịch vụ đã chọn": "Giặt ủi",
    "Trạng thái đơn hàng": "Đã giao",
    "Thời gian đặt hàng": "2025-02-25 12:38:53",
    "Giá tiền": "110,386 VND",
  },
  {
    "Mã đơn hàng": "LAUNDRY943882",
    "Tên khách hàng": "Le Van C",
    "Dịch vụ đã chọn": "Giặt giày",
    "Trạng thái đơn hàng": "Chờ xử lý",
    "Thời gian đặt hàng": "2025-02-25 12:38:53",
    "Giá tiền": "64,153 VND",
  },
  {
    "Mã đơn hàng": "LAUNDRY120857",
    "Tên khách hàng": "Tran Thi B",
    "Dịch vụ đã chọn": "Giặt hấp",
    "Trạng thái đơn hàng": "Chờ xử lý",
    "Thời gian đặt hàng": "2025-02-23 12:38:53",
    "Giá tiền": "98,827 VND",
  },
  {
    "Mã đơn hàng": "LAUNDRY423387",
    "Tên khách hàng": "Le Van C",
    "Dịch vụ đã chọn": "Giặt ủi",
    "Trạng thái đơn hàng": "Đã nhận",
    "Thời gian đặt hàng": "2025-02-18 12:38:53",
    "Giá tiền": "124,356 VND",
  },
  {
    "Mã đơn hàng": "LAUNDRY809467",
    "Tên khách hàng": "Hoang Van E",
    "Dịch vụ đã chọn": "Giặt hấp",
    "Trạng thái đơn hàng": "Đã nhận",
    "Thời gian đặt hàng": "2025-02-24 12:38:53",
    "Giá tiền": "266,489 VND",
  },
  {
    "Mã đơn hàng": "LAUNDRY375578",
    "Tên khách hàng": "Pham Thi D",
    "Dịch vụ đã chọn": "Giặt ủi",
    "Trạng thái đơn hàng": "Đã nhận",
    "Thời gian đặt hàng": "2025-02-23 12:38:53",
    "Giá tiền": "139,603 VND",
  },
];

const drivers = [
  {
    key: "1",
    "Mã tài xế": "DRIVER7778",
    "Tên tài xế": "Lê Văn C",
    "Số đơn hàng đang giao": 3,
  },
  {
    key: "2",
    "Mã tài xế": "DRIVER2604",
    "Tên tài xế": "Phạm Văn D",
    "Số đơn hàng đang giao": 4,
  },
  {
    key: "3",
    "Mã tài xế": "DRIVER6357",
    "Tên tài xế": "Hoàng Thị E",
    "Số đơn hàng đang giao": 4,
  },
  {
    key: "4",
    "Mã tài xế": "DRIVER1317",
    "Tên tài xế": "Hoàng Thị E",
    "Số đơn hàng đang giao": 5,
  },
  {
    key: "5",
    "Mã tài xế": "DRIVER5464",
    "Tên tài xế": "Trần Thị B",
    "Số đơn hàng đang giao": 5,
  },
  {
    key: "6",
    "Mã tài xế": "DRIVER3772",
    "Tên tài xế": "Phạm Văn D",
    "Số đơn hàng đang giao": 2,
  },
  {
    key: "7",
    "Mã tài xế": "DRIVER2825",
    "Tên tài xế": "Phạm Văn D",
    "Số đơn hàng đang giao": 5,
  },
  {
    key: "8",
    "Mã tài xế": "DRIVER5894",
    "Tên tài xế": "Đỗ Văn F",
    "Số đơn hàng đang giao": 5,
  },
  {
    key: "9",
    "Mã tài xế": "DRIVER3542",
    "Tên tài xế": "Bùi Văn H",
    "Số đơn hàng đang giao": 4,
  },
  {
    key: "10",
    "Mã tài xế": "DRIVER5570",
    "Tên tài xế": "Vũ Thị G",
    "Số đơn hàng đang giao": 2,
  },
];

export default { OrderCustomerBooking, drivers };
